{"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failure","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ExitCode","kind":"typeIdentifier","identifier":"doc:\/\/com.SwiftyLab.HelperCoders\/documentation\/ArgumentParser\/ExitCode","preciseIdentifier":"s:14ArgumentParser8ExitCodeV"}]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/argumentparser\/exitcode\/failure"]}],"identifier":{"url":"doc:\/\/com.SwiftyLab.HelperCoders\/documentation\/ArgumentParser\/ExitCode\/failure","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"ArgumentParser"}],"title":"failure","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"failure"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14ArgumentParser8ExitCodeV","text":"ExitCode"}],"symbolKind":"property","roleHeading":"Type Property","externalID":"s:14ArgumentParser8ExitCodeV7failureACvpZ"},"abstract":[{"text":"An exit code that indicates that the command failed.","type":"text"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.SwiftyLab.HelperCoders\/documentation\/ArgumentParser","doc:\/\/com.SwiftyLab.HelperCoders\/documentation\/ArgumentParser\/ExitCode"]]},"references":{"doc://com.SwiftyLab.HelperCoders/documentation/ArgumentParser":{"kind":"symbol","role":"collection","url":"\/documentation\/argumentparser","abstract":[],"title":"ArgumentParser","identifier":"doc:\/\/com.SwiftyLab.HelperCoders\/documentation\/ArgumentParser","type":"topic"},"doc://com.SwiftyLab.HelperCoders/documentation/ArgumentParser/ExitCode/failure":{"role":"symbol","title":"failure","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"failure"},{"text":": ","kind":"text"},{"text":"ExitCode","kind":"typeIdentifier","preciseIdentifier":"s:14ArgumentParser8ExitCodeV"}],"kind":"symbol","identifier":"doc:\/\/com.SwiftyLab.HelperCoders\/documentation\/ArgumentParser\/ExitCode\/failure","type":"topic","abstract":[{"text":"An exit code that indicates that the command failed.","type":"text"}],"url":"\/documentation\/argumentparser\/exitcode\/failure"},"doc://com.SwiftyLab.HelperCoders/documentation/ArgumentParser/ExitCode":{"url":"\/documentation\/argumentparser\/exitcode","identifier":"doc:\/\/com.SwiftyLab.HelperCoders\/documentation\/ArgumentParser\/ExitCode","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"ExitCode","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ExitCode"}],"type":"topic","title":"ExitCode","abstract":[{"text":"An error type that only includes an exit code.","type":"text"}]}}}