{"metadata":{"symbolKind":"property","role":"symbol","title":"message","externalID":"s:14ArgumentParser15ValidationErrorV7messageSSvp","roleHeading":"Instance Property","modules":[{"name":"ArgumentParser"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"message","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.SwiftyLab.HelperCoders\/documentation\/ArgumentParser","doc:\/\/com.SwiftyLab.HelperCoders\/documentation\/ArgumentParser\/ValidationError"]]},"identifier":{"url":"doc:\/\/com.SwiftyLab.HelperCoders\/documentation\/ArgumentParser\/ValidationError\/message","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"message","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":" { get }"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/argumentparser\/validationerror\/message"]}],"abstract":[{"text":"The error message represented by this instance, this string is presented to","type":"text"},{"type":"text","text":" "},{"text":"the user when a ","type":"text"},{"code":"ValidationError","type":"codeVoice"},{"type":"text","text":" is thrown from either; "},{"code":"run()","type":"codeVoice"},{"text":",","type":"text"},{"type":"text","text":" "},{"type":"codeVoice","code":"validate()"},{"text":" or a transform closure.","type":"text"}],"references":{"doc://com.SwiftyLab.HelperCoders/documentation/ArgumentParser/ValidationError":{"navigatorTitle":[{"kind":"identifier","text":"ValidationError"}],"identifier":"doc:\/\/com.SwiftyLab.HelperCoders\/documentation\/ArgumentParser\/ValidationError","url":"\/documentation\/argumentparser\/validationerror","title":"ValidationError","abstract":[{"type":"text","text":"An error type that is presented to the user as an error with parsing their"},{"type":"text","text":" "},{"text":"command-line input.","type":"text"}],"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ValidationError","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://com.SwiftyLab.HelperCoders/documentation/ArgumentParser":{"kind":"symbol","role":"collection","url":"\/documentation\/argumentparser","abstract":[],"title":"ArgumentParser","identifier":"doc:\/\/com.SwiftyLab.HelperCoders\/documentation\/ArgumentParser","type":"topic"},"doc://com.SwiftyLab.HelperCoders/documentation/ArgumentParser/ValidationError/message":{"type":"topic","url":"\/documentation\/argumentparser\/validationerror\/message","role":"symbol","kind":"symbol","title":"message","identifier":"doc:\/\/com.SwiftyLab.HelperCoders\/documentation\/ArgumentParser\/ValidationError\/message","abstract":[{"text":"The error message represented by this instance, this string is presented to","type":"text"},{"text":" ","type":"text"},{"text":"the user when a ","type":"text"},{"code":"ValidationError","type":"codeVoice"},{"type":"text","text":" is thrown from either; "},{"type":"codeVoice","code":"run()"},{"type":"text","text":","},{"text":" ","type":"text"},{"type":"codeVoice","code":"validate()"},{"text":" or a transform closure.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"message","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]}}}